apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ghcr.io/cybc16/nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerconfigjson-github-com
